-- Phase 25 — coords nullable, submission coords, RLS re-assert, + catalog seeds (cigars & lounges).
-- Idempotent: re-running skips rows that already exist (matched by slug).

-- 1) Lounges can now be added without coordinates (geocoded later via the verify flow).
alter table public.lounges alter column lat drop not null;
alter table public.lounges alter column lng drop not null;

-- 2) Carry coordinates captured on the verify form through to approval.
alter table public.lounge_submissions add column if not exists lat numeric(9,6);
alter table public.lounge_submissions add column if not exists lng numeric(9,6);
alter table public.lounge_submissions add column if not exists kind text default 'new';
alter table public.lounge_submissions add column if not exists business_license text;
alter table public.lounge_submissions add column if not exists contact_name text;
alter table public.lounge_submissions add column if not exists claims_ownership boolean default false;

-- 3) Make sure admins can see every submission (verify + new).
drop policy if exists "admins review lounge submissions" on public.lounge_submissions;
create policy "admins review lounge submissions" on public.lounge_submissions
  for all using (exists (select 1 from public.profiles p where p.id = auth.uid() and p.role in ('admin','super_admin')));

-- 4) Seed the Top 300 boutique cigars (skip any slug already present).
insert into public.catalog_cigars (id, brand, name, country, price, size, slug)
select gen_random_uuid(), v.brand, v.name, v.country, v.price, v.size, v.slug from (values
  ('Foundation Cigar Co.','The Tabernacle Robusto','Nicaragua',12.0,'5" x 50','the-tabernacle-robusto'),
  ('Foundation Cigar Co.','The Tabernacle Toro','Nicaragua',13.0,'6" x 52','the-tabernacle-toro'),
  ('Foundation Cigar Co.','The Tabernacle Churchill','Nicaragua',14.0,'7" x 48','the-tabernacle-churchill'),
  ('Foundation Cigar Co.','The Tabernacle Corona','Nicaragua',11.5,'5.5" x 44','the-tabernacle-corona'),
  ('Foundation Cigar Co.','The Tabernacle Lancero','Nicaragua',13.5,'7.5" x 38','the-tabernacle-lancero'),
  ('Foundation Cigar Co.','The Tabernacle Gordo','Nicaragua',14.5,'6" x 60','the-tabernacle-gordo'),
  ('Foundation Cigar Co.','Olmec Claro Robusto','Nicaragua',13.0,'5" x 50','olmec-claro-robusto'),
  ('Foundation Cigar Co.','Olmec Claro Toro','Nicaragua',14.0,'6" x 52','olmec-claro-toro'),
  ('Foundation Cigar Co.','Olmec Claro Churchill','Nicaragua',15.0,'7" x 48','olmec-claro-churchill'),
  ('Foundation Cigar Co.','Olmec Claro Corona','Nicaragua',12.5,'5.5" x 44','olmec-claro-corona'),
  ('Foundation Cigar Co.','Olmec Claro Lancero','Nicaragua',14.5,'7.5" x 38','olmec-claro-lancero'),
  ('Foundation Cigar Co.','Olmec Claro Gordo','Nicaragua',15.5,'6" x 60','olmec-claro-gordo'),
  ('Foundation Cigar Co.','Olmec Maduro Robusto','Nicaragua',13.0,'5" x 50','olmec-maduro-robusto'),
  ('Foundation Cigar Co.','Olmec Maduro Toro','Nicaragua',14.0,'6" x 52','olmec-maduro-toro'),
  ('Foundation Cigar Co.','Olmec Maduro Churchill','Nicaragua',15.0,'7" x 48','olmec-maduro-churchill'),
  ('Foundation Cigar Co.','Olmec Maduro Corona','Nicaragua',12.5,'5.5" x 44','olmec-maduro-corona'),
  ('Foundation Cigar Co.','Olmec Maduro Lancero','Nicaragua',14.5,'7.5" x 38','olmec-maduro-lancero'),
  ('Foundation Cigar Co.','Olmec Maduro Gordo','Nicaragua',15.5,'6" x 60','olmec-maduro-gordo'),
  ('Foundation Cigar Co.','El Güegüense Robusto','Nicaragua',11.5,'5" x 50','el-g-eg-ense-robusto'),
  ('Foundation Cigar Co.','El Güegüense Toro','Nicaragua',12.5,'6" x 52','el-g-eg-ense-toro'),
  ('Foundation Cigar Co.','El Güegüense Churchill','Nicaragua',13.5,'7" x 48','el-g-eg-ense-churchill'),
  ('Foundation Cigar Co.','El Güegüense Corona','Nicaragua',11.0,'5.5" x 44','el-g-eg-ense-corona'),
  ('Foundation Cigar Co.','El Güegüense Lancero','Nicaragua',13.0,'7.5" x 38','el-g-eg-ense-lancero'),
  ('Foundation Cigar Co.','El Güegüense Gordo','Nicaragua',14.0,'6" x 60','el-g-eg-ense-gordo'),
  ('Dunbarton Tobacco & Trust','Sobremesa Brûlée Robusto','Nicaragua',13.5,'5" x 50','sobremesa-br-l-e-robusto'),
  ('Dunbarton Tobacco & Trust','Sobremesa Brûlée Toro','Nicaragua',14.5,'6" x 52','sobremesa-br-l-e-toro'),
  ('Dunbarton Tobacco & Trust','Sobremesa Brûlée Churchill','Nicaragua',15.5,'7" x 48','sobremesa-br-l-e-churchill'),
  ('Dunbarton Tobacco & Trust','Sobremesa Brûlée Corona','Nicaragua',13.0,'5.5" x 44','sobremesa-br-l-e-corona'),
  ('Dunbarton Tobacco & Trust','Sobremesa Brûlée Lancero','Nicaragua',15.0,'7.5" x 38','sobremesa-br-l-e-lancero'),
  ('Dunbarton Tobacco & Trust','Sobremesa Brûlée Gordo','Nicaragua',16.0,'6" x 60','sobremesa-br-l-e-gordo'),
  ('Dunbarton Tobacco & Trust','Mi Querida Ancho Robusto','Nicaragua',12.5,'5" x 50','mi-querida-ancho-robusto'),
  ('Dunbarton Tobacco & Trust','Mi Querida Ancho Toro','Nicaragua',13.5,'6" x 52','mi-querida-ancho-toro'),
  ('Dunbarton Tobacco & Trust','Mi Querida Ancho Churchill','Nicaragua',14.5,'7" x 48','mi-querida-ancho-churchill'),
  ('Dunbarton Tobacco & Trust','Mi Querida Ancho Corona','Nicaragua',12.0,'5.5" x 44','mi-querida-ancho-corona'),
  ('Dunbarton Tobacco & Trust','Mi Querida Ancho Lancero','Nicaragua',14.0,'7.5" x 38','mi-querida-ancho-lancero'),
  ('Dunbarton Tobacco & Trust','Mi Querida Ancho Gordo','Nicaragua',15.0,'6" x 60','mi-querida-ancho-gordo'),
  ('Dunbarton Tobacco & Trust','Sin Compromiso Robusto','Nicaragua',16.0,'5" x 50','sin-compromiso-robusto'),
  ('Dunbarton Tobacco & Trust','Sin Compromiso Toro','Nicaragua',17.0,'6" x 52','sin-compromiso-toro'),
  ('Dunbarton Tobacco & Trust','Sin Compromiso Churchill','Nicaragua',18.0,'7" x 48','sin-compromiso-churchill'),
  ('Dunbarton Tobacco & Trust','Sin Compromiso Corona','Nicaragua',15.5,'5.5" x 44','sin-compromiso-corona'),
  ('Dunbarton Tobacco & Trust','Sin Compromiso Lancero','Nicaragua',17.5,'7.5" x 38','sin-compromiso-lancero'),
  ('Dunbarton Tobacco & Trust','Sin Compromiso Gordo','Nicaragua',18.5,'6" x 60','sin-compromiso-gordo'),
  ('Dunbarton Tobacco & Trust','Muestra de Saka Robusto','Nicaragua',18.0,'5" x 50','muestra-de-saka-robusto'),
  ('Dunbarton Tobacco & Trust','Muestra de Saka Toro','Nicaragua',19.0,'6" x 52','muestra-de-saka-toro'),
  ('Dunbarton Tobacco & Trust','Muestra de Saka Churchill','Nicaragua',20.0,'7" x 48','muestra-de-saka-churchill'),
  ('Dunbarton Tobacco & Trust','Muestra de Saka Corona','Nicaragua',17.5,'5.5" x 44','muestra-de-saka-corona'),
  ('Dunbarton Tobacco & Trust','Muestra de Saka Lancero','Nicaragua',19.5,'7.5" x 38','muestra-de-saka-lancero'),
  ('Dunbarton Tobacco & Trust','Muestra de Saka Gordo','Nicaragua',20.5,'6" x 60','muestra-de-saka-gordo'),
  ('RoMa Craft Tobac','CroMagnon Robusto','Nicaragua',9.5,'5" x 50','cromagnon-robusto'),
  ('RoMa Craft Tobac','CroMagnon Toro','Nicaragua',10.5,'6" x 52','cromagnon-toro'),
  ('RoMa Craft Tobac','CroMagnon Churchill','Nicaragua',11.5,'7" x 48','cromagnon-churchill'),
  ('RoMa Craft Tobac','CroMagnon Corona','Nicaragua',9.0,'5.5" x 44','cromagnon-corona'),
  ('RoMa Craft Tobac','CroMagnon Lancero','Nicaragua',11.0,'7.5" x 38','cromagnon-lancero'),
  ('RoMa Craft Tobac','CroMagnon Gordo','Nicaragua',12.0,'6" x 60','cromagnon-gordo'),
  ('RoMa Craft Tobac','Neanderthal Robusto','Nicaragua',12.0,'5" x 50','neanderthal-robusto'),
  ('RoMa Craft Tobac','Neanderthal Toro','Nicaragua',13.0,'6" x 52','neanderthal-toro'),
  ('RoMa Craft Tobac','Neanderthal Churchill','Nicaragua',14.0,'7" x 48','neanderthal-churchill'),
  ('RoMa Craft Tobac','Neanderthal Corona','Nicaragua',11.5,'5.5" x 44','neanderthal-corona'),
  ('RoMa Craft Tobac','Neanderthal Lancero','Nicaragua',13.5,'7.5" x 38','neanderthal-lancero'),
  ('RoMa Craft Tobac','Neanderthal Gordo','Nicaragua',14.5,'6" x 60','neanderthal-gordo'),
  ('RoMa Craft Tobac','Aquitaine Robusto','Nicaragua',9.5,'5" x 50','aquitaine-robusto'),
  ('RoMa Craft Tobac','Aquitaine Toro','Nicaragua',10.5,'6" x 52','aquitaine-toro'),
  ('RoMa Craft Tobac','Aquitaine Churchill','Nicaragua',11.5,'7" x 48','aquitaine-churchill'),
  ('RoMa Craft Tobac','Aquitaine Corona','Nicaragua',9.0,'5.5" x 44','aquitaine-corona'),
  ('RoMa Craft Tobac','Aquitaine Lancero','Nicaragua',11.0,'7.5" x 38','aquitaine-lancero'),
  ('RoMa Craft Tobac','Aquitaine Gordo','Nicaragua',12.0,'6" x 60','aquitaine-gordo'),
  ('RoMa Craft Tobac','Intemperance EC XVIII Robusto','Nicaragua',8.5,'5" x 50','intemperance-ec-xviii-robusto'),
  ('RoMa Craft Tobac','Intemperance EC XVIII Toro','Nicaragua',9.5,'6" x 52','intemperance-ec-xviii-toro'),
  ('RoMa Craft Tobac','Intemperance EC XVIII Churchill','Nicaragua',10.5,'7" x 48','intemperance-ec-xviii-churchill'),
  ('RoMa Craft Tobac','Intemperance EC XVIII Corona','Nicaragua',8.0,'5.5" x 44','intemperance-ec-xviii-corona'),
  ('RoMa Craft Tobac','Intemperance EC XVIII Lancero','Nicaragua',10.0,'7.5" x 38','intemperance-ec-xviii-lancero'),
  ('RoMa Craft Tobac','Intemperance EC XVIII Gordo','Nicaragua',11.0,'6" x 60','intemperance-ec-xviii-gordo'),
  ('Tatuaje Cigars','Seleccion de Cazador (Brown Label) Robusto','Nicaragua',11.0,'5" x 50','seleccion-de-cazador-brown-label-robusto'),
  ('Tatuaje Cigars','Seleccion de Cazador (Brown Label) Toro','Nicaragua',12.0,'6" x 52','seleccion-de-cazador-brown-label-toro'),
  ('Tatuaje Cigars','Seleccion de Cazador (Brown Label) Churchill','Nicaragua',13.0,'7" x 48','seleccion-de-cazador-brown-label-churchill'),
  ('Tatuaje Cigars','Seleccion de Cazador (Brown Label) Corona','Nicaragua',10.5,'5.5" x 44','seleccion-de-cazador-brown-label-corona'),
  ('Tatuaje Cigars','Seleccion de Cazador (Brown Label) Lancero','Nicaragua',12.5,'7.5" x 38','seleccion-de-cazador-brown-label-lancero'),
  ('Tatuaje Cigars','Seleccion de Cazador (Brown Label) Gordo','Nicaragua',13.5,'6" x 60','seleccion-de-cazador-brown-label-gordo'),
  ('Tatuaje Cigars','Havana VI Robusto','Nicaragua',8.5,'5" x 50','havana-vi-robusto'),
  ('Tatuaje Cigars','Havana VI Toro','Nicaragua',9.5,'6" x 52','havana-vi-toro'),
  ('Tatuaje Cigars','Havana VI Churchill','Nicaragua',10.5,'7" x 48','havana-vi-churchill'),
  ('Tatuaje Cigars','Havana VI Corona','Nicaragua',8.0,'5.5" x 44','havana-vi-corona'),
  ('Tatuaje Cigars','Havana VI Lancero','Nicaragua',10.0,'7.5" x 38','havana-vi-lancero'),
  ('Tatuaje Cigars','Havana VI Gordo','Nicaragua',11.0,'6" x 60','havana-vi-gordo'),
  ('Tatuaje Cigars','Cojonu 2003 Robusto','USA',14.0,'5" x 50','cojonu-2003-robusto'),
  ('Tatuaje Cigars','Cojonu 2003 Toro','USA',15.0,'6" x 52','cojonu-2003-toro'),
  ('Tatuaje Cigars','Cojonu 2003 Churchill','USA',16.0,'7" x 48','cojonu-2003-churchill'),
  ('Tatuaje Cigars','Cojonu 2003 Corona','USA',13.5,'5.5" x 44','cojonu-2003-corona'),
  ('Tatuaje Cigars','Cojonu 2003 Lancero','USA',15.5,'7.5" x 38','cojonu-2003-lancero'),
  ('Tatuaje Cigars','Cojonu 2003 Gordo','USA',16.5,'6" x 60','cojonu-2003-gordo'),
  ('Tatuaje Cigars','Fausto Robusto','Nicaragua',10.0,'5" x 50','fausto-robusto'),
  ('Tatuaje Cigars','Fausto Toro','Nicaragua',11.0,'6" x 52','fausto-toro'),
  ('Tatuaje Cigars','Fausto Churchill','Nicaragua',12.0,'7" x 48','fausto-churchill'),
  ('Tatuaje Cigars','Fausto Corona','Nicaragua',9.5,'5.5" x 44','fausto-corona'),
  ('Tatuaje Cigars','Fausto Lancero','Nicaragua',11.5,'7.5" x 38','fausto-lancero'),
  ('Tatuaje Cigars','Fausto Gordo','Nicaragua',12.5,'6" x 60','fausto-gordo'),
  ('Warped Cigars','La Colmena Robusto','USA',15.0,'5" x 50','la-colmena-robusto'),
  ('Warped Cigars','La Colmena Toro','USA',16.0,'6" x 52','la-colmena-toro'),
  ('Warped Cigars','La Colmena Churchill','USA',17.0,'7" x 48','la-colmena-churchill'),
  ('Warped Cigars','La Colmena Corona','USA',14.5,'5.5" x 44','la-colmena-corona'),
  ('Warped Cigars','La Colmena Lancero','USA',16.5,'7.5" x 38','la-colmena-lancero'),
  ('Warped Cigars','La Colmena Gordo','USA',17.5,'6" x 60','la-colmena-gordo'),
  ('Warped Cigars','Don Reynaldo Robusto','USA',16.0,'5" x 50','don-reynaldo-robusto'),
  ('Warped Cigars','Don Reynaldo Toro','USA',17.0,'6" x 52','don-reynaldo-toro'),
  ('Warped Cigars','Don Reynaldo Churchill','USA',18.0,'7" x 48','don-reynaldo-churchill'),
  ('Warped Cigars','Don Reynaldo Corona','USA',15.5,'5.5" x 44','don-reynaldo-corona'),
  ('Warped Cigars','Don Reynaldo Lancero','USA',17.5,'7.5" x 38','don-reynaldo-lancero'),
  ('Warped Cigars','Don Reynaldo Gordo','USA',18.5,'6" x 60','don-reynaldo-gordo'),
  ('Warped Cigars','Gran Reserva 1988 Robusto','Nicaragua',11.0,'5" x 50','gran-reserva-1988-robusto'),
  ('Warped Cigars','Gran Reserva 1988 Toro','Nicaragua',12.0,'6" x 52','gran-reserva-1988-toro'),
  ('Warped Cigars','Gran Reserva 1988 Churchill','Nicaragua',13.0,'7" x 48','gran-reserva-1988-churchill'),
  ('Warped Cigars','Gran Reserva 1988 Corona','Nicaragua',10.5,'5.5" x 44','gran-reserva-1988-corona'),
  ('Warped Cigars','Gran Reserva 1988 Lancero','Nicaragua',12.5,'7.5" x 38','gran-reserva-1988-lancero'),
  ('Warped Cigars','Gran Reserva 1988 Gordo','Nicaragua',13.5,'6" x 60','gran-reserva-1988-gordo'),
  ('Warped Cigars','Maestro del Tiempo Robusto','Nicaragua',11.5,'5" x 50','maestro-del-tiempo-robusto'),
  ('Warped Cigars','Maestro del Tiempo Toro','Nicaragua',12.5,'6" x 52','maestro-del-tiempo-toro'),
  ('Warped Cigars','Maestro del Tiempo Churchill','Nicaragua',13.5,'7" x 48','maestro-del-tiempo-churchill'),
  ('Warped Cigars','Maestro del Tiempo Corona','Nicaragua',11.0,'5.5" x 44','maestro-del-tiempo-corona'),
  ('Warped Cigars','Maestro del Tiempo Lancero','Nicaragua',13.0,'7.5" x 38','maestro-del-tiempo-lancero'),
  ('Warped Cigars','Maestro del Tiempo Gordo','Nicaragua',14.0,'6" x 60','maestro-del-tiempo-gordo'),
  ('Illusione Cigars','Epernay Robusto','Honduras',11.0,'5" x 50','epernay-robusto'),
  ('Illusione Cigars','Epernay Toro','Honduras',12.0,'6" x 52','epernay-toro'),
  ('Illusione Cigars','Epernay Churchill','Honduras',13.0,'7" x 48','epernay-churchill'),
  ('Illusione Cigars','Epernay Corona','Honduras',10.5,'5.5" x 44','epernay-corona'),
  ('Illusione Cigars','Epernay Lancero','Honduras',12.5,'7.5" x 38','epernay-lancero'),
  ('Illusione Cigars','Epernay Gordo','Honduras',13.5,'6" x 60','epernay-gordo'),
  ('Illusione Cigars','Original Documents Robusto','Nicaragua',10.0,'5" x 50','original-documents-robusto'),
  ('Illusione Cigars','Original Documents Toro','Nicaragua',11.0,'6" x 52','original-documents-toro'),
  ('Illusione Cigars','Original Documents Churchill','Nicaragua',12.0,'7" x 48','original-documents-churchill'),
  ('Illusione Cigars','Original Documents Corona','Nicaragua',9.5,'5.5" x 44','original-documents-corona'),
  ('Illusione Cigars','Original Documents Lancero','Nicaragua',11.5,'7.5" x 38','original-documents-lancero'),
  ('Illusione Cigars','Original Documents Gordo','Nicaragua',12.5,'6" x 60','original-documents-gordo'),
  ('Illusione Cigars','OneOff Robusto','Nicaragua',13.0,'5" x 50','oneoff-robusto'),
  ('Illusione Cigars','OneOff Toro','Nicaragua',14.0,'6" x 52','oneoff-toro'),
  ('Illusione Cigars','OneOff Churchill','Nicaragua',15.0,'7" x 48','oneoff-churchill'),
  ('Illusione Cigars','OneOff Corona','Nicaragua',12.5,'5.5" x 44','oneoff-corona'),
  ('Illusione Cigars','OneOff Lancero','Nicaragua',14.5,'7.5" x 38','oneoff-lancero'),
  ('Illusione Cigars','OneOff Gordo','Nicaragua',15.5,'6" x 60','oneoff-gordo'),
  ('Crowned Heads','Mil Días Robusto','Dominican Republic',11.5,'5" x 50','mil-d-as-robusto'),
  ('Crowned Heads','Mil Días Toro','Dominican Republic',12.5,'6" x 52','mil-d-as-toro'),
  ('Crowned Heads','Mil Días Churchill','Dominican Republic',13.5,'7" x 48','mil-d-as-churchill'),
  ('Crowned Heads','Mil Días Corona','Dominican Republic',11.0,'5.5" x 44','mil-d-as-corona'),
  ('Crowned Heads','Mil Días Lancero','Dominican Republic',13.0,'7.5" x 38','mil-d-as-lancero'),
  ('Crowned Heads','Mil Días Gordo','Dominican Republic',14.0,'6" x 60','mil-d-as-gordo'),
  ('Crowned Heads','Le Carême Robusto','Dominican Republic',10.5,'5" x 50','le-car-me-robusto'),
  ('Crowned Heads','Le Carême Toro','Dominican Republic',11.5,'6" x 52','le-car-me-toro'),
  ('Crowned Heads','Le Carême Churchill','Dominican Republic',12.5,'7" x 48','le-car-me-churchill'),
  ('Crowned Heads','Le Carême Corona','Dominican Republic',10.0,'5.5" x 44','le-car-me-corona'),
  ('Crowned Heads','Le Carême Lancero','Dominican Republic',12.0,'7.5" x 38','le-car-me-lancero'),
  ('Crowned Heads','Le Carême Gordo','Dominican Republic',13.0,'6" x 60','le-car-me-gordo'),
  ('Crowned Heads','Four Kicks Robusto','Dominican Republic',9.5,'5" x 50','four-kicks-robusto'),
  ('Crowned Heads','Four Kicks Toro','Dominican Republic',10.5,'6" x 52','four-kicks-toro'),
  ('Crowned Heads','Four Kicks Churchill','Dominican Republic',11.5,'7" x 48','four-kicks-churchill'),
  ('Crowned Heads','Four Kicks Corona','Dominican Republic',9.0,'5.5" x 44','four-kicks-corona'),
  ('Crowned Heads','Four Kicks Lancero','Dominican Republic',11.0,'7.5" x 38','four-kicks-lancero'),
  ('Crowned Heads','Four Kicks Gordo','Dominican Republic',12.0,'6" x 60','four-kicks-gordo'),
  ('Crowned Heads','Juarez Robusto','Dominican Republic',8.0,'5" x 50','juarez-robusto'),
  ('Crowned Heads','Juarez Toro','Dominican Republic',9.0,'6" x 52','juarez-toro'),
  ('Crowned Heads','Juarez Churchill','Dominican Republic',10.0,'7" x 48','juarez-churchill'),
  ('Crowned Heads','Juarez Corona','Dominican Republic',7.5,'5.5" x 44','juarez-corona'),
  ('Crowned Heads','Juarez Lancero','Dominican Republic',9.5,'7.5" x 38','juarez-lancero'),
  ('Crowned Heads','Juarez Gordo','Dominican Republic',10.5,'6" x 60','juarez-gordo'),
  ('Black Label Trading Co.','Last Rites Robusto','Nicaragua',11.0,'5" x 50','last-rites-robusto'),
  ('Black Label Trading Co.','Last Rites Toro','Nicaragua',12.0,'6" x 52','last-rites-toro'),
  ('Black Label Trading Co.','Last Rites Churchill','Nicaragua',13.0,'7" x 48','last-rites-churchill'),
  ('Black Label Trading Co.','Last Rites Corona','Nicaragua',10.5,'5.5" x 44','last-rites-corona'),
  ('Black Label Trading Co.','Last Rites Lancero','Nicaragua',12.5,'7.5" x 38','last-rites-lancero'),
  ('Black Label Trading Co.','Last Rites Gordo','Nicaragua',13.5,'6" x 60','last-rites-gordo'),
  ('Black Label Trading Co.','Royalty Robusto','Nicaragua',10.0,'5" x 50','royalty-robusto'),
  ('Black Label Trading Co.','Royalty Toro','Nicaragua',11.0,'6" x 52','royalty-toro'),
  ('Black Label Trading Co.','Royalty Churchill','Nicaragua',12.0,'7" x 48','royalty-churchill'),
  ('Black Label Trading Co.','Royalty Corona','Nicaragua',9.5,'5.5" x 44','royalty-corona'),
  ('Black Label Trading Co.','Royalty Lancero','Nicaragua',11.5,'7.5" x 38','royalty-lancero'),
  ('Black Label Trading Co.','Royalty Gordo','Nicaragua',12.5,'6" x 60','royalty-gordo'),
  ('Black Works Studio','NBK Robusto','Nicaragua',11.5,'5" x 50','nbk-robusto'),
  ('Black Works Studio','NBK Toro','Nicaragua',12.5,'6" x 52','nbk-toro'),
  ('Black Works Studio','NBK Churchill','Nicaragua',13.5,'7" x 48','nbk-churchill'),
  ('Black Works Studio','NBK Corona','Nicaragua',11.0,'5.5" x 44','nbk-corona'),
  ('Black Works Studio','NBK Lancero','Nicaragua',13.0,'7.5" x 38','nbk-lancero'),
  ('Black Works Studio','NBK Gordo','Nicaragua',14.0,'6" x 60','nbk-gordo'),
  ('Caldwell Cigar Co.','The King is Dead Robusto','Dominican Republic',11.0,'5" x 50','the-king-is-dead-robusto'),
  ('Caldwell Cigar Co.','The King is Dead Toro','Dominican Republic',12.0,'6" x 52','the-king-is-dead-toro'),
  ('Caldwell Cigar Co.','The King is Dead Churchill','Dominican Republic',13.0,'7" x 48','the-king-is-dead-churchill'),
  ('Caldwell Cigar Co.','The King is Dead Corona','Dominican Republic',10.5,'5.5" x 44','the-king-is-dead-corona'),
  ('Caldwell Cigar Co.','The King is Dead Lancero','Dominican Republic',12.5,'7.5" x 38','the-king-is-dead-lancero'),
  ('Caldwell Cigar Co.','The King is Dead Gordo','Dominican Republic',13.5,'6" x 60','the-king-is-dead-gordo'),
  ('Caldwell Cigar Co.','Long Live the King Robusto','Dominican Republic',12.0,'5" x 50','long-live-the-king-robusto'),
  ('Caldwell Cigar Co.','Long Live the King Toro','Dominican Republic',13.0,'6" x 52','long-live-the-king-toro'),
  ('Caldwell Cigar Co.','Long Live the King Churchill','Dominican Republic',14.0,'7" x 48','long-live-the-king-churchill'),
  ('Caldwell Cigar Co.','Long Live the King Corona','Dominican Republic',11.5,'5.5" x 44','long-live-the-king-corona'),
  ('Caldwell Cigar Co.','Long Live the King Lancero','Dominican Republic',13.5,'7.5" x 38','long-live-the-king-lancero'),
  ('Caldwell Cigar Co.','Long Live the King Gordo','Dominican Republic',14.5,'6" x 60','long-live-the-king-gordo'),
  ('Caldwell Cigar Co.','Blind Man''s Bluff Robusto','Honduras',9.0,'5" x 50','blind-man-s-bluff-robusto'),
  ('Caldwell Cigar Co.','Blind Man''s Bluff Toro','Honduras',10.0,'6" x 52','blind-man-s-bluff-toro'),
  ('Caldwell Cigar Co.','Blind Man''s Bluff Churchill','Honduras',11.0,'7" x 48','blind-man-s-bluff-churchill'),
  ('Caldwell Cigar Co.','Blind Man''s Bluff Corona','Honduras',8.5,'5.5" x 44','blind-man-s-bluff-corona'),
  ('Caldwell Cigar Co.','Blind Man''s Bluff Lancero','Honduras',10.5,'7.5" x 38','blind-man-s-bluff-lancero'),
  ('Caldwell Cigar Co.','Blind Man''s Bluff Gordo','Honduras',11.5,'6" x 60','blind-man-s-bluff-gordo'),
  ('HVC Cigars','Hot Cake Robusto','Nicaragua',9.0,'5" x 50','hot-cake-robusto'),
  ('HVC Cigars','Hot Cake Toro','Nicaragua',10.0,'6" x 52','hot-cake-toro'),
  ('HVC Cigars','Hot Cake Churchill','Nicaragua',11.0,'7" x 48','hot-cake-churchill'),
  ('HVC Cigars','Hot Cake Corona','Nicaragua',8.5,'5.5" x 44','hot-cake-corona'),
  ('HVC Cigars','Hot Cake Lancero','Nicaragua',10.5,'7.5" x 38','hot-cake-lancero'),
  ('HVC Cigars','Hot Cake Gordo','Nicaragua',11.5,'6" x 60','hot-cake-gordo'),
  ('HVC Cigars','Selección No. 1 Robusto','Nicaragua',10.5,'5" x 50','selecci-n-no-1-robusto'),
  ('HVC Cigars','Selección No. 1 Toro','Nicaragua',11.5,'6" x 52','selecci-n-no-1-toro'),
  ('HVC Cigars','Selección No. 1 Churchill','Nicaragua',12.5,'7" x 48','selecci-n-no-1-churchill'),
  ('HVC Cigars','Selección No. 1 Corona','Nicaragua',10.0,'5.5" x 44','selecci-n-no-1-corona'),
  ('HVC Cigars','Selección No. 1 Lancero','Nicaragua',12.0,'7.5" x 38','selecci-n-no-1-lancero'),
  ('HVC Cigars','Selección No. 1 Gordo','Nicaragua',13.0,'6" x 60','selecci-n-no-1-gordo'),
  ('Aladino (JRE Tobacco)','Corojo Reserva Robusto','Honduras',12.0,'5" x 50','corojo-reserva-robusto'),
  ('Aladino (JRE Tobacco)','Corojo Reserva Toro','Honduras',13.0,'6" x 52','corojo-reserva-toro'),
  ('Aladino (JRE Tobacco)','Corojo Reserva Churchill','Honduras',14.0,'7" x 48','corojo-reserva-churchill'),
  ('Aladino (JRE Tobacco)','Corojo Reserva Corona','Honduras',11.5,'5.5" x 44','corojo-reserva-corona'),
  ('Aladino (JRE Tobacco)','Corojo Reserva Lancero','Honduras',13.5,'7.5" x 38','corojo-reserva-lancero'),
  ('Aladino (JRE Tobacco)','Corojo Reserva Gordo','Honduras',14.5,'6" x 60','corojo-reserva-gordo'),
  ('Aladino (JRE Tobacco)','Vintage Selection Robusto','Honduras',10.0,'5" x 50','vintage-selection-robusto'),
  ('Aladino (JRE Tobacco)','Vintage Selection Toro','Honduras',11.0,'6" x 52','vintage-selection-toro'),
  ('Aladino (JRE Tobacco)','Vintage Selection Churchill','Honduras',12.0,'7" x 48','vintage-selection-churchill'),
  ('Aladino (JRE Tobacco)','Vintage Selection Corona','Honduras',9.5,'5.5" x 44','vintage-selection-corona'),
  ('Aladino (JRE Tobacco)','Vintage Selection Lancero','Honduras',11.5,'7.5" x 38','vintage-selection-lancero'),
  ('Aladino (JRE Tobacco)','Vintage Selection Gordo','Honduras',12.5,'6" x 60','vintage-selection-gordo'),
  ('Aladino (JRE Tobacco)','Cameroon Robusto','Honduras',9.5,'5" x 50','cameroon-robusto'),
  ('Aladino (JRE Tobacco)','Cameroon Toro','Honduras',10.5,'6" x 52','cameroon-toro'),
  ('Aladino (JRE Tobacco)','Cameroon Churchill','Honduras',11.5,'7" x 48','cameroon-churchill'),
  ('Aladino (JRE Tobacco)','Cameroon Corona','Honduras',9.0,'5.5" x 44','cameroon-corona'),
  ('Aladino (JRE Tobacco)','Cameroon Lancero','Honduras',11.0,'7.5" x 38','cameroon-lancero'),
  ('Aladino (JRE Tobacco)','Cameroon Gordo','Honduras',12.0,'6" x 60','cameroon-gordo'),
  ('Southern Draw','Rose of Sharon Robusto','Nicaragua',11.0,'5" x 50','rose-of-sharon-robusto'),
  ('Southern Draw','Rose of Sharon Toro','Nicaragua',12.0,'6" x 52','rose-of-sharon-toro'),
  ('Southern Draw','Rose of Sharon Churchill','Nicaragua',13.0,'7" x 48','rose-of-sharon-churchill'),
  ('Southern Draw','Rose of Sharon Corona','Nicaragua',10.5,'5.5" x 44','rose-of-sharon-corona'),
  ('Southern Draw','Rose of Sharon Lancero','Nicaragua',12.5,'7.5" x 38','rose-of-sharon-lancero'),
  ('Southern Draw','Rose of Sharon Gordo','Nicaragua',13.5,'6" x 60','rose-of-sharon-gordo'),
  ('Southern Draw','Jacobs Ladder Robusto','Nicaragua',11.5,'5" x 50','jacobs-ladder-robusto'),
  ('Southern Draw','Jacobs Ladder Toro','Nicaragua',12.5,'6" x 52','jacobs-ladder-toro'),
  ('Southern Draw','Jacobs Ladder Churchill','Nicaragua',13.5,'7" x 48','jacobs-ladder-churchill'),
  ('Southern Draw','Jacobs Ladder Corona','Nicaragua',11.0,'5.5" x 44','jacobs-ladder-corona'),
  ('Southern Draw','Jacobs Ladder Lancero','Nicaragua',13.0,'7.5" x 38','jacobs-ladder-lancero'),
  ('Southern Draw','Jacobs Ladder Gordo','Nicaragua',14.0,'6" x 60','jacobs-ladder-gordo'),
  ('Aganorsa Leaf','Supreme Leaf Robusto','Nicaragua',12.5,'5" x 50','supreme-leaf-robusto'),
  ('Aganorsa Leaf','Supreme Leaf Toro','Nicaragua',13.5,'6" x 52','supreme-leaf-toro'),
  ('Aganorsa Leaf','Supreme Leaf Churchill','Nicaragua',14.5,'7" x 48','supreme-leaf-churchill'),
  ('Aganorsa Leaf','Supreme Leaf Corona','Nicaragua',12.0,'5.5" x 44','supreme-leaf-corona'),
  ('Aganorsa Leaf','Supreme Leaf Lancero','Nicaragua',14.0,'7.5" x 38','supreme-leaf-lancero'),
  ('Aganorsa Leaf','Supreme Leaf Gordo','Nicaragua',15.0,'6" x 60','supreme-leaf-gordo'),
  ('Aganorsa Leaf','Rare Leaf Reserve Robusto','Nicaragua',10.5,'5" x 50','rare-leaf-reserve-robusto'),
  ('Aganorsa Leaf','Rare Leaf Reserve Toro','Nicaragua',11.5,'6" x 52','rare-leaf-reserve-toro'),
  ('Aganorsa Leaf','Rare Leaf Reserve Churchill','Nicaragua',12.5,'7" x 48','rare-leaf-reserve-churchill'),
  ('Aganorsa Leaf','Rare Leaf Reserve Corona','Nicaragua',10.0,'5.5" x 44','rare-leaf-reserve-corona'),
  ('Aganorsa Leaf','Rare Leaf Reserve Lancero','Nicaragua',12.0,'7.5" x 38','rare-leaf-reserve-lancero'),
  ('Aganorsa Leaf','Rare Leaf Reserve Gordo','Nicaragua',13.0,'6" x 60','rare-leaf-reserve-gordo'),
  ('Plasencia 1865','Alma Fuerte Robusto','Nicaragua',21.0,'5" x 50','alma-fuerte-robusto'),
  ('Plasencia 1865','Alma Fuerte Toro','Nicaragua',22.0,'6" x 52','alma-fuerte-toro'),
  ('Plasencia 1865','Alma Fuerte Churchill','Nicaragua',23.0,'7" x 48','alma-fuerte-churchill'),
  ('Plasencia 1865','Alma Fuerte Corona','Nicaragua',20.5,'5.5" x 44','alma-fuerte-corona'),
  ('Plasencia 1865','Alma Fuerte Lancero','Nicaragua',22.5,'7.5" x 38','alma-fuerte-lancero'),
  ('Plasencia 1865','Alma Fuerte Gordo','Nicaragua',23.5,'6" x 60','alma-fuerte-gordo'),
  ('Plasencia 1865','Alma del Fuego Robusto','Nicaragua',16.0,'5" x 50','alma-del-fuego-robusto'),
  ('Plasencia 1865','Alma del Fuego Toro','Nicaragua',17.0,'6" x 52','alma-del-fuego-toro'),
  ('Plasencia 1865','Alma del Fuego Churchill','Nicaragua',18.0,'7" x 48','alma-del-fuego-churchill'),
  ('Plasencia 1865','Alma del Fuego Corona','Nicaragua',15.5,'5.5" x 44','alma-del-fuego-corona'),
  ('Plasencia 1865','Alma del Fuego Lancero','Nicaragua',17.5,'7.5" x 38','alma-del-fuego-lancero'),
  ('Plasencia 1865','Alma del Fuego Gordo','Nicaragua',18.5,'6" x 60','alma-del-fuego-gordo'),
  ('Viaje Cigar Co.','Skull and Bones Robusto','Nicaragua',12.0,'5" x 50','skull-and-bones-robusto'),
  ('Viaje Cigar Co.','Skull and Bones Toro','Nicaragua',13.0,'6" x 52','skull-and-bones-toro'),
  ('Viaje Cigar Co.','Skull and Bones Churchill','Nicaragua',14.0,'7" x 48','skull-and-bones-churchill'),
  ('Viaje Cigar Co.','Skull and Bones Corona','Nicaragua',11.5,'5.5" x 44','skull-and-bones-corona'),
  ('Viaje Cigar Co.','Skull and Bones Lancero','Nicaragua',13.5,'7.5" x 38','skull-and-bones-lancero'),
  ('Viaje Cigar Co.','Skull and Bones Gordo','Nicaragua',14.5,'6" x 60','skull-and-bones-gordo'),
  ('Crux Cigars','Epicure Robusto','Nicaragua',10.0,'5" x 50','epicure-robusto'),
  ('Crux Cigars','Epicure Toro','Nicaragua',11.0,'6" x 52','epicure-toro'),
  ('Crux Cigars','Epicure Churchill','Nicaragua',12.0,'7" x 48','epicure-churchill'),
  ('Crux Cigars','Epicure Corona','Nicaragua',9.5,'5.5" x 44','epicure-corona'),
  ('Crux Cigars','Epicure Lancero','Nicaragua',11.5,'7.5" x 38','epicure-lancero'),
  ('Crux Cigars','Epicure Gordo','Nicaragua',12.5,'6" x 60','epicure-gordo'),
  ('Crux Cigars','Bull & Bear Robusto','Nicaragua',11.0,'5" x 50','bull-bear-robusto'),
  ('Crux Cigars','Bull & Bear Toro','Nicaragua',12.0,'6" x 52','bull-bear-toro'),
  ('Crux Cigars','Bull & Bear Churchill','Nicaragua',13.0,'7" x 48','bull-bear-churchill'),
  ('Crux Cigars','Bull & Bear Corona','Nicaragua',10.5,'5.5" x 44','bull-bear-corona'),
  ('Crux Cigars','Bull & Bear Lancero','Nicaragua',12.5,'7.5" x 38','bull-bear-lancero'),
  ('Crux Cigars','Bull & Bear Gordo','Nicaragua',13.5,'6" x 60','bull-bear-gordo'),
  ('Cavalier Genève','White Series Robusto','Honduras',10.5,'5" x 50','white-series-robusto'),
  ('Cavalier Genève','White Series Toro','Honduras',11.5,'6" x 52','white-series-toro'),
  ('Cavalier Genève','White Series Churchill','Honduras',12.5,'7" x 48','white-series-churchill'),
  ('Cavalier Genève','White Series Corona','Honduras',10.0,'5.5" x 44','white-series-corona'),
  ('Cavalier Genève','White Series Lancero','Honduras',12.0,'7.5" x 38','white-series-lancero'),
  ('Cavalier Genève','White Series Gordo','Honduras',13.0,'6" x 60','white-series-gordo'),
  ('Fratello Cigars','Classico Robusto','Nicaragua',9.5,'5" x 50','classico-robusto'),
  ('Fratello Cigars','Classico Toro','Nicaragua',10.5,'6" x 52','classico-toro'),
  ('Fratello Cigars','Classico Churchill','Nicaragua',11.5,'7" x 48','classico-churchill'),
  ('Fratello Cigars','Classico Corona','Nicaragua',9.0,'5.5" x 44','classico-corona'),
  ('Fratello Cigars','Classico Lancero','Nicaragua',11.0,'7.5" x 38','classico-lancero'),
  ('Fratello Cigars','Classico Gordo','Nicaragua',12.0,'6" x 60','classico-gordo'),
  ('Rojas Cigars','Street Tacos Barbacoa Robusto','Nicaragua',8.5,'5" x 50','street-tacos-barbacoa-robusto'),
  ('Rojas Cigars','Street Tacos Barbacoa Toro','Nicaragua',9.5,'6" x 52','street-tacos-barbacoa-toro'),
  ('Rojas Cigars','Street Tacos Barbacoa Churchill','Nicaragua',10.5,'7" x 48','street-tacos-barbacoa-churchill'),
  ('Rojas Cigars','Street Tacos Barbacoa Corona','Nicaragua',8.0,'5.5" x 44','street-tacos-barbacoa-corona'),
  ('Rojas Cigars','Street Tacos Barbacoa Lancero','Nicaragua',10.0,'7.5" x 38','street-tacos-barbacoa-lancero'),
  ('Rojas Cigars','Street Tacos Barbacoa Gordo','Nicaragua',11.0,'6" x 60','street-tacos-barbacoa-gordo')
) as v(brand,name,country,price,size,slug)
where not exists (select 1 from public.catalog_cigars c where c.slug = v.slug);

-- 5) Seed the USA lounges (no coordinates yet; map pin appears once geocoded).
insert into public.lounges (id, slug, name, address, city, state, lat, lng, verified, phone, email, website)
select gen_random_uuid(), v.slug, v.name, v.address, v.city, v.state, null, null, false, v.phone, null, v.website from (values
  ('grand-havana-room-new-york-ny','Grand Havana Room','666 5th Ave #39','New York','NY','(212) 245-1600','https://grandhavana.com'),
  ('grand-havana-room-beverly-hills-ca','Grand Havana Room','301 N Canon Dr','Beverly Hills','CA','(310) 274-8100','https://grandhavana.com'),
  ('davidoff-of-geneva-las-vegas-nv','Davidoff of Geneva','3200 Las Vegas Blvd S #1245','Las Vegas','NV','(702) 473-5001','https://davidoffcigarbarlv.com'),
  ('davidoff-of-geneva-new-york-ny','Davidoff of Geneva','515 Madison Ave','New York','NY','(212) 751-9060','https://us.davidoffgeneva.com'),
  ('churchill-bar-at-the-brown-palace-denver-co','Churchill Bar at The Brown Palace','321 17th St','Denver','CO','(303) 297-3111','https://brownpalace.com'),
  ('corona-cigar-co-diamond-crown-lounge-orlando-fl','Corona Cigar Co. & Diamond Crown Lounge','127 S Orange Ave','Orlando','FL','(407) 404-5344','https://coronacigar.com'),
  ('burn-by-rocky-patel-naples-fl','Burn by Rocky Patel','9110 Strada Pl Suite 6160','Naples','FL','(239) 653-9013','https://burnbyrockypatel.com'),
  ('eight-cigar-lounge-las-vegas-nv','Eight Cigar Lounge','3000 S Las Vegas Blvd','Las Vegas','NV','(702) 676-7405','https://eightloungelv.com'),
  ('club-macanudo-new-york-ny','Club Macanudo','26 E 63rd St','New York','NY','(212) 752-8200','https://clubmacanudo.com'),
  ('cigars-international-superstore-bethlehem-pa','Cigars International Superstore','4078 Nazareth Pike','Bethlehem','PA','(484) 895-3933','https://cigarsinternational.com'),
  ('cigars-international-superstore-orlando-fl','Cigars International Superstore','4158 Conroy Rd','Orlando','FL','(407) 675-5513','https://cigarsinternational.com'),
  ('creekside-cigar-co-maineville-oh','Creekside Cigar Co.','1381 US-22','Maineville','OH','(513) 630-1044','https://creeksidecigarco.com'),
  ('club-macanudo-bossier-city-la','Club Macanudo','777 Margaritaville Way','Bossier City','LA','(318) 698-7109','https://clubmacanudo.com'),
  ('x-at-one-ocean-miami-beach-fl','X at One Ocean','One Ocean, South of Fifth','Miami Beach','FL','Private Membership','https://Private Membership'),
  ('twin-peaks-cigar-bar-shenandoah-tx','Twin Peaks Cigar Bar','18310 I-45','Shenandoah','TX','(936) 273-8946','https://twinpeaksrestaurant.com'),
  ('casa-fuente-las-vegas-nv','Casa Fuente','3500 Las Vegas Blvd S','Las Vegas','NV','(702) 731-5051','https://casafuente.com'),
  ('ashton-cigar-bar-philadelphia-pa','Ashton Cigar Bar','1522 Walnut St','Philadelphia','PA','(267) 350-0000','https://ashtoncigarbar.com'),
  ('red-phone-booth-atlanta-ga','Red Phone Booth','17 Andrew Young International Blvd NE','Atlanta','GA','(404) 228-7528','https://redphonebooth.com')
) as v(slug,name,address,city,state,phone,website)
where not exists (select 1 from public.lounges l where l.slug = v.slug);
