-- Phase 102 — ABC Fine Wine & Spirits FL locations with on-site humidors, as retailers.
-- Coordinates pending geocode (lat/lng null). Idempotent on slug.
insert into public.lounges (slug, name, address, city, state, lat, lng, website, venue_type, verified) values
  ("abc-fine-wine-spirits-abc-060-17th-street-causeway-fort-lauderdale-fl","ABC Fine Wine & Spirits - 17Th Street Causeway","901 SE 17Th Street","Fort Lauderdale","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-079-34th-blvd-gainesville-fl","ABC Fine Wine & Spirits - 34Th Blvd","5820 NW 34Th Blvd","Gainesville","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-035-4th-street-st-pete-fl","ABC Fine Wine & Spirits - 4Th Street","3535 4Th St. N","St. Pete","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-136-altamonte-springs-altamonte-springs-fl","ABC Fine Wine & Spirits - Altamonte Springs","776 W State Road 436","Altamonte Springs","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-217-apalachee-parkway-tallahassee-fl","ABC Fine Wine & Spirits - Apalachee Parkway","3005 Apalachee Pkwy","Tallahassee","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-086-apollo-beach-apollo-beach-fl","ABC Fine Wine & Spirits - Apollo Beach","6178 N Us Highway 41","Apollo Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-191-atlantic-beach-atlantic-beach-fl","ABC Fine Wine & Spirits - Atlantic Beach","295 Royal Palm Dr.","Atlantic Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-080-avalon-park-orlando-fl","ABC Fine Wine & Spirits - Avalon Park","14806 E Colonial Drive","Orlando","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-152-bee-ridge-sarasota-fl","ABC Fine Wine & Spirits - Bee Ridge","2720 Bee Ridge Road","Sarasota","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-114-boynton-beach-west-boynton-beach-fl","ABC Fine Wine & Spirits - Boynton Beach West","8601 Boynton Beach Blvd","Boynton Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-085-brandon-brandon-fl","ABC Fine Wine & Spirits - Brandon","1405 E Brandon Blvd","Brandon","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-155-cape-canaveral-cape-canaveral-fl","ABC Fine Wine & Spirits - Cape Canaveral","6020 N Atlantic Ave","Cape Canaveral","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-098-cape-coral-cape-coral-fl","ABC Fine Wine & Spirits - Cape Coral","2220 Del Prado Blvd.","Cape Coral","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-096-cape-coral-north-cape-coral-fl","ABC Fine Wine & Spirits - Cape Coral North","1513 SW Pine Island Rd.","Cape Coral","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-095-carrollwood-tampa-fl","ABC Fine Wine & Spirits - Carrollwood","14729 N Dale Mabry Hwy","Tampa","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-173-cesery-jacksonville-fl","ABC Fine Wine & Spirits - Cesery","2621 Cesery Blvd.","Jacksonville","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-144-charlotte-harbor-port-charlotte-fl","ABC Fine Wine & Spirits - Charlotte Harbor","4250 Tamiami Trail","Port Charlotte","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-055-clermont-clermont-fl","ABC Fine Wine & Spirits - Clermont","1395 East Highway 50","Clermont","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-123-cocoa-beach-cocoa-beach-fl","ABC Fine Wine & Spirits - Cocoa Beach","555 N Orlando Ave","Cocoa Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-149-college-park-orlando-fl","ABC Fine Wine & Spirits - College Park","3333 Edgewater Dr.","Orlando","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-092-college-rd-ocala-fl","ABC Fine Wine & Spirits - College Rd","2595 SW College Rd","Ocala","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-151-crystal-river-crystal-river-fl","ABC Fine Wine & Spirits - Crystal River","822 Us Hwy 19 SE","Crystal River","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-041-daytona-beach-shores-daytona-beach-shores-fl","ABC Fine Wine & Spirits - Daytona Beach Shores","3332 S Atlantic Ave.","Daytona Beach Shores","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-131-deland-deland-fl","ABC Fine Wine & Spirits - Deland","1400 S Woodland Blvd.","Deland","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-165-delray-beach-delray-beach-fl","ABC Fine Wine & Spirits - Delray Beach","6180 W Atlantic Ave","Delray Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-200-destin-destin-fl","ABC Fine Wine & Spirits - Destin","34715 Emerald Coast Parkway","Destin","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-005-disney-west-kissimmee-fl","ABC Fine Wine & Spirits - Disney West","3187 Black Lake Road","Kissimmee","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-054-doral-doral-fl","ABC Fine Wine & Spirits - Doral","8050 NW 36Th St","Doral","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-193-dunn-ave-jacksonville-fl","ABC Fine Wine & Spirits - Dunn Ave","963 Dunn Ave.","Jacksonville","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-174-durbin-creek-crossing-st-johns-fl","ABC Fine Wine & Spirits - Durbin Creek Crossing","259 Harper Ln.","St. Johns","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-211-east-boca-boca-raton-fl","ABC Fine Wine & Spirits - East Boca","6998 N Federal Hwy","Boca Raton","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-074-estero-estero-fl","ABC Fine Wine & Spirits - Estero","21700 S Tamiami Trail","Estero","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-172-fernandina-beach-fernandina-beach-fl","ABC Fine Wine & Spirits - Fernandina Beach","474574 Sr 200","Fernandina Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-182-fleming-island-fleming-island-fl","ABC Fine Wine & Spirits - Fleming Island","1811 Eastwest Parkway","Fleming Island","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-207-ft-lauderdale-oakland-park-fl","ABC Fine Wine & Spirits - Ft Lauderdale","3355 North Federal Highway","Oakland Park","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-075-ft-myers-fort-myers-fl","ABC Fine Wine & Spirits - Ft Myers","14725 S Tamiami Trail","Fort Myers","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-076-ft-myers-summerlin-fort-myers-fl","ABC Fine Wine & Spirits - Ft. Myers/Summerlin","10981 Saxum Drive","Fort Myers","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-132-gandy-blvd-tampa-fl","ABC Fine Wine & Spirits - Gandy Blvd","3110 W Gandy Blvd","Tampa","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-209-glades-road-boca-raton-fl","ABC Fine Wine & Spirits - Glades Road","9894 Glades Rd","Boca Raton","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-063-haines-city-haines-city-fl","ABC Fine Wine & Spirits - Haines City","701 Us Hwy 17-92 W","Haines City","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-128-hudson-hudson-fl","ABC Fine Wine & Spirits - Hudson","14248 Us Hwy 19 N","Hudson","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-099-immokalee-rd-naples-fl","ABC Fine Wine & Spirits - Immokalee Rd.","1000 Crosspoint Dr.","Naples","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-020-indialantic-indialantic-fl","ABC Fine Wine & Spirits - Indialantic","300 N Miramar Ave","Indialantic","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-153-inverness-inverness-fl","ABC Fine Wine & Spirits - Inverness","1795 W Main St.","Inverness","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-187-jax-beach-jacksonville-beach-fl","ABC Fine Wine & Spirits - Jax Beach","608 Beach Blvd.","Jacksonville Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-162-jupiter-jupiter-fl","ABC Fine Wine & Spirits - Jupiter","1260 W Indiantown Road","Jupiter","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-004-lake-buena-vista-orlando-fl","ABC Fine Wine & Spirits - Lake Buena Vista","11951 So. Apopka-Vineland Rd","Orlando","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-196-lake-city-lake-city-fl","ABC Fine Wine & Spirits - Lake City","1491 Us Hwy 90 W","Lake City","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-137-lake-mary-lake-mary-fl","ABC Fine Wine & Spirits - Lake Mary","980 Rinehart Rd","Lake Mary","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-032-lake-nona-orlando-fl","ABC Fine Wine & Spirits - Lake Nona","12254 Narcoossee Rd","Orlando","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-059-lake-wales-lake-wales-fl","ABC Fine Wine & Spirits - Lake Wales","23231 Us Hwy 27","Lake Wales","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-167-lake-worth-lake-worth-fl","ABC Fine Wine & Spirits - Lake Worth","5852 South State Road 7","Lake Worth","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-111-lakewood-ranch-bradenton-fl","ABC Fine Wine & Spirits - Lakewood Ranch","11720 State Road 64 E","Bradenton","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-189-lane-ave-jacksonville-fl","ABC Fine Wine & Spirits - Lane Ave","1143 Lane Ave. S","Jacksonville","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-077-largo-largo-fl","ABC Fine Wine & Spirits - Largo","1756 Missouri Ave N","Largo","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-150-leesburg-leesburg-fl","ABC Fine Wine & Spirits - Leesburg","1808 Us 27","Leesburg","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-073-lehigh-acres-fort-myers-fl","ABC Fine Wine & Spirits - Lehigh Acres","11280 Sr 82","Fort Myers","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-134-loop-kissimmee-fl","ABC Fine Wine & Spirits - Loop","3300 N John Young Pkwy","Kissimmee","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-140-manatee-ave-bradenton-fl","ABC Fine Wine & Spirits - Manatee Ave","5810 Manatee Ave. W","Bradenton","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-158-marco-island-marco-island-fl","ABC Fine Wine & Spirits - Marco Island","725 Bald Eagle Drive","Marco Island","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-064-merritt-island-merritt-island-fl","ABC Fine Wine & Spirits - Merritt Island","424 E.Merritt Island Cswy","Merritt Island","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-212-miami-miami-fl","ABC Fine Wine & Spirits - Miami","12620 SW 120Th St","Miami","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-210-midtown-tallahassee-fl","ABC Fine Wine & Spirits - Midtown","1930 Thomasville Rd","Tallahassee","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-056-miramar-parkway-miramar-fl","ABC Fine Wine & Spirits - Miramar Parkway","16941 Miramar Parkway","Miramar","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-113-moccasin-wallow-palmetto-fl","ABC Fine Wine & Spirits - Moccasin Wallow","4925 Moccasin Wallow Rd","Palmetto","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-028-mt-dora-mt-dora-fl","ABC Fine Wine & Spirits - Mt. Dora","19065 Us Highway 441","Mt Dora","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-203-navarre-navarre-fl","ABC Fine Wine & Spirits - Navarre","8315 Mikajack Avenue","Navarre","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-027-new-smyrna-new-smyrna-beach-fl","ABC Fine Wine & Spirits - New Smyrna","2360 Highway 44","New Smyrna Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-112-newberry-rd-gainesville-fl","ABC Fine Wine & Spirits - Newberry Rd","6612 Newberry Rd. W","Gainesville","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-046-north-port-north-port-fl","ABC Fine Wine & Spirits - North Port","4250 Aidan Lane","North Port","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-201-northlake-blvd-palm-beach-gardens-fl","ABC Fine Wine & Spirits - Northlake Blvd","4155 Northlake Blvd","Palm Beach Gardens","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-003-obt-orlando-fl","ABC Fine Wine & Spirits - Obt","5895 S Orange Blsm Trail","Orlando","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-052-ocoee-ocoee-fl","ABC Fine Wine & Spirits - Ocoee","10835 West Colonial Drive","Ocoee","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-192-orange-park-orange-park-fl","ABC Fine Wine & Spirits - Orange Park","426 Blanding Blvd.","Orange Park","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-145-orange-michigan-orlando-fl","ABC Fine Wine & Spirits - Orange/Michigan","2726 S Orange Ave.","Orlando","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-023-ormond-beach-ormond-beach-fl","ABC Fine Wine & Spirits - Ormond Beach","725 S Yonge St","Ormond Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-081-oviedo-oviedo-fl","ABC Fine Wine & Spirits - Oviedo","801 Oviedo Mall Boulevard","Oviedo","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-065-palatka-palatka-fl","ABC Fine Wine & Spirits - Palatka","2527 Reid St.","Palatka","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-006-palm-bay-palm-bay-fl","ABC Fine Wine & Spirits - Palm Bay","4980 Babcock St. NE","Palm Bay","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-197-palm-coast-palm-coast-fl","ABC Fine Wine & Spirits - Palm Coast","224 Palm Coast Pkwy NE","Palm Coast","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-218-panama-city-beach-panama-city-beach-fl","ABC Fine Wine & Spirits - Panama City Beach","11699 Panama City Beach Prkw","Panama City Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-164-pembroke-pines-pembroke-pines-fl","ABC Fine Wine & Spirits - Pembroke Pines","10798 Pines Blvd","Pembroke Pines","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-199-pensacola-pensacola-fl","ABC Fine Wine & Spirits - Pensacola","5052 Bayou Boulevard","Pensacola","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-157-pompano-pompano-beach-fl","ABC Fine Wine & Spirits - Pompano","1350 NE 23Rd Street","Pompano Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-195-ponte-vedra-beach-ponte-vedra-beach-fl","ABC Fine Wine & Spirits - Ponte Vedra Beach","175 Village Main Street","Ponte Vedra Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-142-port-orange-port-orange-fl","ABC Fine Wine & Spirits - Port Orange","1198 Dunlawton Ave","Port Orange","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-040-port-st-lucie-port-st-lucie-fl","ABC Fine Wine & Spirits - Port St. Lucie","2091 SW Gatlin Blvd","Port St. Lucie","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-194-roosevelt-blvd-jacksonville-fl","ABC Fine Wine & Spirits - Roosevelt Blvd","6313 Roosevelt Blvd.","Jacksonville","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-204-royal-palm-beach-royal-palm-beach-fl","ABC Fine Wine & Spirits - Royal Palm Beach","11999 Southern Blvd.","Royal Palm Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-185-san-jose-jacksonville-fl","ABC Fine Wine & Spirits - San Jose","9436 San Jose Blvd.","Jacksonville","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-018-satellite-beach-satellite-beach-fl","ABC Fine Wine & Spirits - Satellite Beach","1426 S Hwy A1A","Satellite Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-050-sawgrass-mill-sunrise-fl","ABC Fine Wine & Spirits - Sawgrass Mill","2611 North Flamingo Road","Sunrise","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-148-sebring-sebring-fl","ABC Fine Wine & Spirits - Sebring","2311 U S Hwy 27 North","Sebring","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-038-seminole-seminole-fl","ABC Fine Wine & Spirits - Seminole","11153 Park Blvd","Seminole","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-118-silver-springs-blvd-ocala-fl","ABC Fine Wine & Spirits - Silver Springs Blvd","4111 NE Silver Springs Blvd.","Ocala","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-053-south-lakeland-lakeland-fl","ABC Fine Wine & Spirits - South Lakeland","4319 So. Florida Ave","Lakeland","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-147-south-semoran-orlando-fl","ABC Fine Wine & Spirits - South Semoran","2322 S Semoran Blvd.","Orlando","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-159-spring-hill-spring-hill-fl","ABC Fine Wine & Spirits - Spring Hill","4120 Commercial Way","Spring Hill","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-190-st-augustine-st-augustine-fl","ABC Fine Wine & Spirits - St. Augustine","1790 Us 1 South","St. Augustine","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-133-st-cloud-st-cloud-fl","ABC Fine Wine & Spirits - St. Cloud","3555 13Th Street","St Cloud","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-160-stuart-stuart-fl","ABC Fine Wine & Spirits - Stuart","1540 SE Federal Hwy","Stuart","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-154-the-villages-lady-lake-fl","ABC Fine Wine & Spirits - The Villages","865 N Us-27/441","Lady Lake","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-215-thomasville-kerry-fores-tallahassee-fl","ABC Fine Wine & Spirits - Thomasville/Kerry Fores","5454 Thomasville Road","Tallahassee","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-069-titusville-titusville-fl","ABC Fine Wine & Spirits - Titusville","1239 S Washington Ave.","Titusville","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-094-town-and-country-tampa-fl","ABC Fine Wine & Spirits - Town And Country","11615 W Hillsborough Ave.","Tampa","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-175-town-center-jacksonville-fl","ABC Fine Wine & Spirits - Town Center","4838 Gate Parkway North","Jacksonville","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-072-treasure-island-treasure-island-fl","ABC Fine Wine & Spirits - Treasure Island","204 107Th Ave.","Treasure Island","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-107-trinity-odessa-fl","ABC Fine Wine & Spirits - Trinity","11868 State Road 54","Odessa","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-049-tyrone-square-st-pete-fl","ABC Fine Wine & Spirits - Tyrone Square","2855 66Th Street North","St. Pete","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-025-university-aloma-winter-park-fl","ABC Fine Wine & Spirits - University/Aloma","399 N Semoran Blvd.","Winter Park","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-105-university-tuttle-sarasota-fl","ABC Fine Wine & Spirits - University/Tuttle","8470 37Th St E","Sarasota","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-143-us-41-s-bradenton-bradenton-fl","ABC Fine Wine & Spirits - Us 41 S. Bradenton","6307 14Th St. W","Bradenton","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-161-us-41-south-naples-naples-fl","ABC Fine Wine & Spirits - Us 41 South Naples","2755 East Tamiami Trail","Naples","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-106-venice-venice-fl","ABC Fine Wine & Spirits - Venice","1741 S Tamiami Trail","Venice","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-042-vero-east-vero-beach-fl","ABC Fine Wine & Spirits - Vero East","602 21St Street","Vero Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-043-vero-west-vero-beach-fl","ABC Fine Wine & Spirits - Vero West","5905 20Th Street","Vero Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-017-viera-suntree-melbourne-fl","ABC Fine Wine & Spirits - Viera/Suntree","55 Interlachen Rd","Melbourne","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-019-w-kennedy-tampa-fl","ABC Fine Wine & Spirits - W. Kennedy","3015 W Kennedy Blvd.","Tampa","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-163-waterford-lakes-orlando-fl","ABC Fine Wine & Spirits - Waterford Lakes","750 S Alafaya Trl","Orlando","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-138-wesley-chapel-wesley-chapel-fl","ABC Fine Wine & Spirits - Wesley Chapel","1845 Bruce B Downs Blvd.","Wesley Chapel","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-091-west-palm-west-palm-beach-fl","ABC Fine Wine & Spirits - West Palm","3319 S Dixie Hwy","West Palm Beach","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-139-wildwood-wildwood-fl","ABC Fine Wine & Spirits - Wildwood","5607 Seven Mile Drive","Wildwood","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-016-winter-garden-winter-garden-fl","ABC Fine Wine & Spirits - Winter Garden","4110 Winter Garden Vineland Road","Winter Garden","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-014-winter-park-orlando-fl","ABC Fine Wine & Spirits - Winter Park","1855 East Winter Park Road","Orlando","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-071-winter-park-village-winter-park-fl","ABC Fine Wine & Spirits - Winter Park Village","401 N Orlando Ave.","Winter Park","FL",null,null,'https://www.abcfws.com','retail',false),
  ("abc-fine-wine-spirits-abc-181-world-golf-village-st-augustine-fl","ABC Fine Wine & Spirits - World Golf Village","140 Registry Blvd","St Augustine","FL",null,null,'https://www.abcfws.com','retail',false)
on conflict (slug) do nothing;
